#server:
#  port: 80
#spring:
#  jpa:
#    generate-ddl: true
#  main:
#    allow-bean-definition-overriding: true
#  #    hibernate:
#  #      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://localhost:5432/practice
#    username: postgres
#    password: root
server:
  port: 80
spring:
  jpa:
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  #    hibernate:
  #      ddl-auto: update
  datasource:
    url: jdbc:postgres://yyypussanfgror:e07e60a65e9868680c01a50b0004eec3bbb5316ef400412f907add541cf8fbf0@ec2-3-217-113-25.compute-1.amazonaws.com:5432/dcntia271d9ofq
    username: yyypussanfgror
    password: e07e60a65e9868680c01a50b0004eec3bbb5316ef400412f907add541cf8fbf0